### ISSUE TITLE
Proxy error: Could not proxy request /api/auth from localhost:3000 to http://localhost:5000. [1] See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED). [1] [1] Proxy error: Could not proxy request /api/users from localhost:3000 to http://localhost:5000.

### ISSUE THREAD

**Issue by Nanyte25** [bradtraversy/devconnector_2.0#208]
HI I seem to be getting this error consistency on start-up not suere if its front not talking to backend issue or mongo related?

```

> react-scripts start
[1]
[0] /Users/markfreer/repos/devconnector_2.0/node_modules/config/lib/config.js:812
[0]     throw new Error("Cannot parse config file: '" + fullFilename + "': " + e3);
[0]     ^
[0]
[0] Error: Cannot parse config file: '/Users/markfreer/repos/devconnector_2.0/config/default.js': SyntaxError: Unexpected token ':'
[0]     at Config.util.parseFile (/Users/markfreer/repos/devconnector_2.0/node_modules/config/lib/config.js:812:11)
[0]     at /Users/markfreer/repos/devconnector_2.0/node_modules/config/lib/config.js:619:26
[0]     at Array.forEach (<anonymous>)
[0]     at Config.util.loadFileConfigs (/Users/markfreer/repos/devconnector_2.0/node_modules/config/lib/config.js:618:16)
[0]     at new Config (/Users/markfreer/repos/devconnector_2.0/node_modules/config/lib/config.js:116:27)
[0]     at Object.<anonymous> (/Users/markfreer/repos/devconnector_2.0/node_modules/config/lib/config.js:1459:31)
[0]     at Module._compile (internal/modules/cjs/loader.js:1251:30)
[0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
[0]     at Module.load (internal/modules/cjs/loader.js:1100:32)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:962:14)
[0]     at Module.require (internal/modules/cjs/loader.js:1140:19)
[0]     at require (internal/modules/cjs/helpers.js:75:18)
[0]     at Object.<anonymous> (/Users/markfreer/repos/devconnector_2.0/config/db.js:2:16)
[0]     at Module._compile (internal/modules/cjs/loader.js:1251:30)
[0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
[0]     at Module.load (internal/modules/cjs/loader.js:1100:32)
[0] [nodemon] app crashed - waiting for file changes before starting...
[1] ℹ ｢wds｣: Project is running at http://192.168.8.123/
[1] ℹ ｢wds｣: webpack output is served from
[1] ℹ ｢wds｣: Content not from webpack is served from /Users/markfreer/repos/devconnector_2.0/client/public
[1] ℹ ｢wds｣: 404s will fallback to /
[1] Starting the development server...
[1]
[1] Compiled successfully!
[1]
[1] You can now view client in the browser.
[1]
[1]   Local:            http://localhost:3000
[1]   On Your Network:  http://192.168.8.123:3000
[1]
[1] Note that the development build is not optimized.
[1] To create a production build, use npm run build.
[1]
[1] Proxy error: Could not proxy request /api/auth from localhost:3000 to http://localhost:5000.
[1] See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).
[1]
[1] Proxy error: Could not proxy request /api/users from localhost:3000 to http://localhost:5000.
[1] See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).
[1]

```

**Comment by bushblade** [comment]
Hi @Nanyte25 
The error is saying that the config package cannot parse your config/default.js
That needs to be a JSON file, so config.json
You need to provide your own config files and credentials, the repo code doesn't include that, please make sure to read the README.
As this doesn't appear to be an issue with the repository code, I'll close as an issue.

**Comment by Nanyte25** [comment]
thank's saw that now
