### ISSUE TITLE
connectDB is not a function

### ISSUE THREAD

**Issue by aribambang** [bradtraversy/devconnector_2.0#34]
I'm having the issue and I have it as exports, still not seeing connectDB as a function

my GitHub repo: https://github.com/aribambang/medusa

TypeError: connectDB is not a function
    at Object.<anonymous> (/Users/aribambang/development/node/medusa/server.js:6:1)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:826:10)
    at internal/main/run_main_module.js:17:11

https://github.com/bradtraversy/devconnector_2.0/blob/7a3d9d19231548825a9b2d64304b3a8638b4580c/server.js#L8

**Comment by aribambang** [comment]
> I'm having the issue and I have it as exports, still not seeing connectDB as a function
> 
> my GitHub repo: https://github.com/aribambang/medusa
> 
> TypeError: connectDB is not a function
> at Object. (/Users/aribambang/development/node/medusa/server.js:6:1)
> at Module._compile (internal/modules/cjs/loader.js:759:30)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
> at Module.load (internal/modules/cjs/loader.js:628:32)
> at Function.Module._load (internal/modules/cjs/loader.js:555:12)
> at Function.Module.runMain (internal/modules/cjs/loader.js:826:10)
> at internal/main/run_main_module.js:17:11
> 
> https://github.com/bradtraversy/devconnector_2.0/blob/7a3d9d19231548825a9b2d64304b3a8638b4580c/server.js#L8

I fixed it, I forgot module.exports not module.export
