### ISSUE TITLE
This error comes in terminal while submitting empty create profile form. 

### ISSUE THREAD

**Issue by SapnaDorbi** [bradtraversy/devconnector_2.0#56]
Cannot set headers after they are sent to the client
[0] (node:13549) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
[0]     at ServerResponse.setHeader (_http_outgoing.js:470:11)
[0]     at ServerResponse.header (/opt/lampp/htdocs/practice-stuff/DevConnector/node_modules/express/lib/response.js:771:10)
[0]     at ServerResponse.send (/opt/lampp/htdocs/practice-stuff/DevConnector/node_modules/express/lib/response.js:170:12)
[0]     at router.get (/opt/lampp/htdocs/practice-stuff/DevConnector/routes/api/profile.js:26:19)
[0]     at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by Omar-Handouk** [comment]
Plese paste  your profile code here first.

But as an intution your server is send two or more response..

For instance you may want to check if a user is valid first, in your care this is what you  may have done
```js
if (userNotValid){
    res.status(401).send('Unauthorized');
}

res.status(200).send('Created profile successfully');
```

The problem with the above code is that you function send status 401 but does not terminate the function it continue to end the function and sends 200. This causes the error

So to fix this issue just add a return before the first response. i.e

```js
if (userNotValid){
    return res.status(401).send('Unauthorized');
}

res.status(200).send('Created profile successfully');
```

**Comment by bushblade** [comment]
As this has gone a little stale, has lack of actionable information and doesn't appear to be an issue with the current repo code, I'm closing this issue.
