### ISSUE TITLE
Express Tye Error in server.js file

### ISSUE THREAD

**Issue by vsthakur101** [bradtraversy/devconnector_2.0#77]
const app = express();
[0]             ^
[0]
[0] TypeError: express is not a function
  at Module._compile (internal/modules/cjs/loader.js:955:30)
[0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:723:14)
[0]     at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
[0]     at internal/main/run_main_module.js:17:11
[0] [nodemon] app crashed - waiting for file changes before starting...

**Comment by bushblade** [comment]
Hi, can you please explain the steps to reproduce this error, and describe your development environment and set up?
Also have you installed all the dependencies for the app?

**Comment by vsthakur101** [comment]
I followed all steps according to README and install all dependencies and after that I type <npm run dev> then it shows this error. I also used <npm audit fix --force> command.

**Comment by bushblade** [comment]
As of today I can clone the repo, add a config/default.json and successfully run the app with no errors, so I am unable to reproduce your issue.
Can you provide an example or a link to your projects repository.
Also provide a little more info about your development environment, there is very little information to go on here.
If you're getting an error of `express is not a function` that suggests to me the packages are not installed correctly, is your package.json the same as the current in this repository?

**Comment by vsthakur101** [comment]
Yes and i also update and re-install express

**Comment by vsthakur101** [comment]
I resolve this error.
Thank you for helping me.
